// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AdminDeleteSubEventEp } from '../src/api/adminDeleteSubEvent';
import type { default as _AdminGetDataEp } from '../src/api/adminGetData';
import type { default as _AdminGetEmailLogEp } from '../src/api/adminGetEmailLog';
import type { default as _AdminGetPresenceEp } from '../src/api/adminGetPresence';
import type { default as _AdminGetSupportEp } from '../src/api/adminGetSupport';
import type { default as _AdminGetTicketEp } from '../src/api/adminGetTicket';
import type { default as _AdminMoveRoleEp } from '../src/api/adminMoveRole';
import type { default as _AdminNoteTicketEp } from '../src/api/adminNoteTicket';
import type { default as _AdminReplyTicketEp } from '../src/api/adminReplyTicket';
import type { default as _AdminSaveMemberEp } from '../src/api/adminSaveMember';
import type { default as _AdminSaveShowEp } from '../src/api/adminSaveShow';
import type { default as _AdminSaveSubEventEp } from '../src/api/adminSaveSubEvent';
import type { default as _AdminSendMessageEp } from '../src/api/adminSendMessage';
import type { default as _AdminSendReminderEp } from '../src/api/adminSendReminder';
import type { default as _AdminSetMaintainerEp } from '../src/api/adminSetMaintainer';
import type { default as _AdminUpdateTicketEp } from '../src/api/adminUpdateTicket';
import type { default as _CheckEmailEp } from '../src/api/checkEmail';
import type { default as _GetCalendarEp } from '../src/api/getCalendar';
import type { default as _GetMeEp } from '../src/api/getMe';
import type { default as _GetMyEventsEp } from '../src/api/getMyEvents';
import type { default as _GetPresenceEp } from '../src/api/getPresence';
import type { default as _GetPublicCalendarEp } from '../src/api/getPublicCalendar';
import type { default as _GetStageLayoutEp } from '../src/api/getStageLayout';
import type { default as _PresenceApprovalEp } from '../src/api/presenceApproval';
import type { default as _PresenceDecisionEp } from '../src/api/presenceDecision';
import type { default as _PresenceEndEp } from '../src/api/presenceEnd';
import type { default as _PresenceRequestEp } from '../src/api/presenceRequest';
import type { default as _PresenceStartEp } from '../src/api/presenceStart';
import type { default as _SetAttendanceEp } from '../src/api/setAttendance';
import type { default as _SetShowResponseEp } from '../src/api/setShowResponse';
import type { default as _SubmitSupportEp } from '../src/api/submitSupport';
import type { default as _SupportEscalateEp } from '../src/api/supportEscalate';
import type { default as _UpdateMyProfileEp } from '../src/api/updateMyProfile';

type _AdminDeleteSubEventCfg = typeof _AdminDeleteSubEventEp;
export type AdminDeleteSubEventInputType = NonNullable<_AdminDeleteSubEventCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminDeleteSubEventCfg['execute']>[0]['input'];
export type AdminDeleteSubEventOutputType = Awaited<ReturnType<_AdminDeleteSubEventCfg['execute']>>;
export const adminDeleteSubEvent = createCaller<AdminDeleteSubEventInputType, AdminDeleteSubEventOutputType>('adminDeleteSubEvent');

type _AdminGetDataCfg = typeof _AdminGetDataEp;
export type AdminGetDataInputType = NonNullable<_AdminGetDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetDataCfg['execute']>[0]['input'];
export type AdminGetDataOutputType = Awaited<ReturnType<_AdminGetDataCfg['execute']>>;
export const adminGetData = createCaller<AdminGetDataInputType, AdminGetDataOutputType>('adminGetData');

type _AdminGetEmailLogCfg = typeof _AdminGetEmailLogEp;
export type AdminGetEmailLogInputType = NonNullable<_AdminGetEmailLogCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetEmailLogCfg['execute']>[0]['input'];
export type AdminGetEmailLogOutputType = Awaited<ReturnType<_AdminGetEmailLogCfg['execute']>>;
export const adminGetEmailLog = createCaller<AdminGetEmailLogInputType, AdminGetEmailLogOutputType>('adminGetEmailLog');

type _AdminGetPresenceCfg = typeof _AdminGetPresenceEp;
export type AdminGetPresenceInputType = NonNullable<_AdminGetPresenceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetPresenceCfg['execute']>[0]['input'];
export type AdminGetPresenceOutputType = Awaited<ReturnType<_AdminGetPresenceCfg['execute']>>;
export const adminGetPresence = createCaller<AdminGetPresenceInputType, AdminGetPresenceOutputType>('adminGetPresence');

type _AdminGetSupportCfg = typeof _AdminGetSupportEp;
export type AdminGetSupportInputType = NonNullable<_AdminGetSupportCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetSupportCfg['execute']>[0]['input'];
export type AdminGetSupportOutputType = Awaited<ReturnType<_AdminGetSupportCfg['execute']>>;
export const adminGetSupport = createCaller<AdminGetSupportInputType, AdminGetSupportOutputType>('adminGetSupport');

type _AdminGetTicketCfg = typeof _AdminGetTicketEp;
export type AdminGetTicketInputType = NonNullable<_AdminGetTicketCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetTicketCfg['execute']>[0]['input'];
export type AdminGetTicketOutputType = Awaited<ReturnType<_AdminGetTicketCfg['execute']>>;
export const adminGetTicket = createCaller<AdminGetTicketInputType, AdminGetTicketOutputType>('adminGetTicket');

type _AdminMoveRoleCfg = typeof _AdminMoveRoleEp;
export type AdminMoveRoleInputType = NonNullable<_AdminMoveRoleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminMoveRoleCfg['execute']>[0]['input'];
export type AdminMoveRoleOutputType = Awaited<ReturnType<_AdminMoveRoleCfg['execute']>>;
export const adminMoveRole = createCaller<AdminMoveRoleInputType, AdminMoveRoleOutputType>('adminMoveRole');

type _AdminNoteTicketCfg = typeof _AdminNoteTicketEp;
export type AdminNoteTicketInputType = NonNullable<_AdminNoteTicketCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminNoteTicketCfg['execute']>[0]['input'];
export type AdminNoteTicketOutputType = Awaited<ReturnType<_AdminNoteTicketCfg['execute']>>;
export const adminNoteTicket = createCaller<AdminNoteTicketInputType, AdminNoteTicketOutputType>('adminNoteTicket');

type _AdminReplyTicketCfg = typeof _AdminReplyTicketEp;
export type AdminReplyTicketInputType = NonNullable<_AdminReplyTicketCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminReplyTicketCfg['execute']>[0]['input'];
export type AdminReplyTicketOutputType = Awaited<ReturnType<_AdminReplyTicketCfg['execute']>>;
export const adminReplyTicket = createCaller<AdminReplyTicketInputType, AdminReplyTicketOutputType>('adminReplyTicket');

type _AdminSaveMemberCfg = typeof _AdminSaveMemberEp;
export type AdminSaveMemberInputType = NonNullable<_AdminSaveMemberCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSaveMemberCfg['execute']>[0]['input'];
export type AdminSaveMemberOutputType = Awaited<ReturnType<_AdminSaveMemberCfg['execute']>>;
export const adminSaveMember = createCaller<AdminSaveMemberInputType, AdminSaveMemberOutputType>('adminSaveMember');

type _AdminSaveShowCfg = typeof _AdminSaveShowEp;
export type AdminSaveShowInputType = NonNullable<_AdminSaveShowCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSaveShowCfg['execute']>[0]['input'];
export type AdminSaveShowOutputType = Awaited<ReturnType<_AdminSaveShowCfg['execute']>>;
export const adminSaveShow = createCaller<AdminSaveShowInputType, AdminSaveShowOutputType>('adminSaveShow');

type _AdminSaveSubEventCfg = typeof _AdminSaveSubEventEp;
export type AdminSaveSubEventInputType = NonNullable<_AdminSaveSubEventCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSaveSubEventCfg['execute']>[0]['input'];
export type AdminSaveSubEventOutputType = Awaited<ReturnType<_AdminSaveSubEventCfg['execute']>>;
export const adminSaveSubEvent = createCaller<AdminSaveSubEventInputType, AdminSaveSubEventOutputType>('adminSaveSubEvent');

type _AdminSendMessageCfg = typeof _AdminSendMessageEp;
export type AdminSendMessageInputType = NonNullable<_AdminSendMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSendMessageCfg['execute']>[0]['input'];
export type AdminSendMessageOutputType = Awaited<ReturnType<_AdminSendMessageCfg['execute']>>;
export const adminSendMessage = createCaller<AdminSendMessageInputType, AdminSendMessageOutputType>('adminSendMessage');

type _AdminSendReminderCfg = typeof _AdminSendReminderEp;
export type AdminSendReminderInputType = NonNullable<_AdminSendReminderCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSendReminderCfg['execute']>[0]['input'];
export type AdminSendReminderOutputType = Awaited<ReturnType<_AdminSendReminderCfg['execute']>>;
export const adminSendReminder = createCaller<AdminSendReminderInputType, AdminSendReminderOutputType>('adminSendReminder');

type _AdminSetMaintainerCfg = typeof _AdminSetMaintainerEp;
export type AdminSetMaintainerInputType = NonNullable<_AdminSetMaintainerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSetMaintainerCfg['execute']>[0]['input'];
export type AdminSetMaintainerOutputType = Awaited<ReturnType<_AdminSetMaintainerCfg['execute']>>;
export const adminSetMaintainer = createCaller<AdminSetMaintainerInputType, AdminSetMaintainerOutputType>('adminSetMaintainer');

type _AdminUpdateTicketCfg = typeof _AdminUpdateTicketEp;
export type AdminUpdateTicketInputType = NonNullable<_AdminUpdateTicketCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminUpdateTicketCfg['execute']>[0]['input'];
export type AdminUpdateTicketOutputType = Awaited<ReturnType<_AdminUpdateTicketCfg['execute']>>;
export const adminUpdateTicket = createCaller<AdminUpdateTicketInputType, AdminUpdateTicketOutputType>('adminUpdateTicket');

type _CheckEmailCfg = typeof _CheckEmailEp;
export type CheckEmailInputType = NonNullable<_CheckEmailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CheckEmailCfg['execute']>[0]['input'];
export type CheckEmailOutputType = Awaited<ReturnType<_CheckEmailCfg['execute']>>;
export const checkEmail = createCaller<CheckEmailInputType, CheckEmailOutputType>('checkEmail');

type _GetCalendarCfg = typeof _GetCalendarEp;
export type GetCalendarInputType = NonNullable<_GetCalendarCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCalendarCfg['execute']>[0]['input'];
export type GetCalendarOutputType = Awaited<ReturnType<_GetCalendarCfg['execute']>>;
export const getCalendar = createCaller<GetCalendarInputType, GetCalendarOutputType>('getCalendar');

type _GetMeCfg = typeof _GetMeEp;
export type GetMeInputType = NonNullable<_GetMeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMeCfg['execute']>[0]['input'];
export type GetMeOutputType = Awaited<ReturnType<_GetMeCfg['execute']>>;
export const getMe = createCaller<GetMeInputType, GetMeOutputType>('getMe');

type _GetMyEventsCfg = typeof _GetMyEventsEp;
export type GetMyEventsInputType = NonNullable<_GetMyEventsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMyEventsCfg['execute']>[0]['input'];
export type GetMyEventsOutputType = Awaited<ReturnType<_GetMyEventsCfg['execute']>>;
export const getMyEvents = createCaller<GetMyEventsInputType, GetMyEventsOutputType>('getMyEvents');

type _GetPresenceCfg = typeof _GetPresenceEp;
export type GetPresenceInputType = NonNullable<_GetPresenceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPresenceCfg['execute']>[0]['input'];
export type GetPresenceOutputType = Awaited<ReturnType<_GetPresenceCfg['execute']>>;
export const getPresence = createCaller<GetPresenceInputType, GetPresenceOutputType>('getPresence');

type _GetPublicCalendarCfg = typeof _GetPublicCalendarEp;
export type GetPublicCalendarInputType = NonNullable<_GetPublicCalendarCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPublicCalendarCfg['execute']>[0]['input'];
export type GetPublicCalendarOutputType = Awaited<ReturnType<_GetPublicCalendarCfg['execute']>>;
export const getPublicCalendar = createCaller<GetPublicCalendarInputType, GetPublicCalendarOutputType>('getPublicCalendar');

type _GetStageLayoutCfg = typeof _GetStageLayoutEp;
export type GetStageLayoutInputType = NonNullable<_GetStageLayoutCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetStageLayoutCfg['execute']>[0]['input'];
export type GetStageLayoutOutputType = Awaited<ReturnType<_GetStageLayoutCfg['execute']>>;
export const getStageLayout = createCaller<GetStageLayoutInputType, GetStageLayoutOutputType>('getStageLayout');

type _PresenceApprovalCfg = typeof _PresenceApprovalEp;
export type PresenceApprovalInputType = NonNullable<_PresenceApprovalCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PresenceApprovalCfg['execute']>[0]['input'];
export type PresenceApprovalOutputType = Awaited<ReturnType<_PresenceApprovalCfg['execute']>>;
export const presenceApproval = createCaller<PresenceApprovalInputType, PresenceApprovalOutputType>('presenceApproval');

type _PresenceDecisionCfg = typeof _PresenceDecisionEp;
export type PresenceDecisionInputType = NonNullable<_PresenceDecisionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PresenceDecisionCfg['execute']>[0]['input'];
export type PresenceDecisionOutputType = Awaited<ReturnType<_PresenceDecisionCfg['execute']>>;
export const presenceDecision = createCaller<PresenceDecisionInputType, PresenceDecisionOutputType>('presenceDecision');

type _PresenceEndCfg = typeof _PresenceEndEp;
export type PresenceEndInputType = NonNullable<_PresenceEndCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PresenceEndCfg['execute']>[0]['input'];
export type PresenceEndOutputType = Awaited<ReturnType<_PresenceEndCfg['execute']>>;
export const presenceEnd = createCaller<PresenceEndInputType, PresenceEndOutputType>('presenceEnd');

type _PresenceRequestCfg = typeof _PresenceRequestEp;
export type PresenceRequestInputType = NonNullable<_PresenceRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PresenceRequestCfg['execute']>[0]['input'];
export type PresenceRequestOutputType = Awaited<ReturnType<_PresenceRequestCfg['execute']>>;
export const presenceRequest = createCaller<PresenceRequestInputType, PresenceRequestOutputType>('presenceRequest');

type _PresenceStartCfg = typeof _PresenceStartEp;
export type PresenceStartInputType = NonNullable<_PresenceStartCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PresenceStartCfg['execute']>[0]['input'];
export type PresenceStartOutputType = Awaited<ReturnType<_PresenceStartCfg['execute']>>;
export const presenceStart = createCaller<PresenceStartInputType, PresenceStartOutputType>('presenceStart');

type _SetAttendanceCfg = typeof _SetAttendanceEp;
export type SetAttendanceInputType = NonNullable<_SetAttendanceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SetAttendanceCfg['execute']>[0]['input'];
export type SetAttendanceOutputType = Awaited<ReturnType<_SetAttendanceCfg['execute']>>;
export const setAttendance = createCaller<SetAttendanceInputType, SetAttendanceOutputType>('setAttendance');

type _SetShowResponseCfg = typeof _SetShowResponseEp;
export type SetShowResponseInputType = NonNullable<_SetShowResponseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SetShowResponseCfg['execute']>[0]['input'];
export type SetShowResponseOutputType = Awaited<ReturnType<_SetShowResponseCfg['execute']>>;
export const setShowResponse = createCaller<SetShowResponseInputType, SetShowResponseOutputType>('setShowResponse');

type _SubmitSupportCfg = typeof _SubmitSupportEp;
export type SubmitSupportInputType = NonNullable<_SubmitSupportCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitSupportCfg['execute']>[0]['input'];
export type SubmitSupportOutputType = Awaited<ReturnType<_SubmitSupportCfg['execute']>>;
export const submitSupport = createCaller<SubmitSupportInputType, SubmitSupportOutputType>('submitSupport');

type _SupportEscalateCfg = typeof _SupportEscalateEp;
export type SupportEscalateInputType = NonNullable<_SupportEscalateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SupportEscalateCfg['execute']>[0]['input'];
export type SupportEscalateOutputType = Awaited<ReturnType<_SupportEscalateCfg['execute']>>;
export const supportEscalate = createCaller<SupportEscalateInputType, SupportEscalateOutputType>('supportEscalate');

type _UpdateMyProfileCfg = typeof _UpdateMyProfileEp;
export type UpdateMyProfileInputType = NonNullable<_UpdateMyProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateMyProfileCfg['execute']>[0]['input'];
export type UpdateMyProfileOutputType = Awaited<ReturnType<_UpdateMyProfileCfg['execute']>>;
export const updateMyProfile = createCaller<UpdateMyProfileInputType, UpdateMyProfileOutputType>('updateMyProfile');


export const api = {
  adminDeleteSubEvent,
  adminGetData,
  adminGetEmailLog,
  adminGetPresence,
  adminGetSupport,
  adminGetTicket,
  adminMoveRole,
  adminNoteTicket,
  adminReplyTicket,
  adminSaveMember,
  adminSaveShow,
  adminSaveSubEvent,
  adminSendMessage,
  adminSendReminder,
  adminSetMaintainer,
  adminUpdateTicket,
  checkEmail,
  getCalendar,
  getMe,
  getMyEvents,
  getPresence,
  getPublicCalendar,
  getStageLayout,
  presenceApproval,
  presenceDecision,
  presenceEnd,
  presenceRequest,
  presenceStart,
  setAttendance,
  setShowResponse,
  submitSupport,
  supportEscalate,
  updateMyProfile,
};
